aws_profile  = "root"
aws_region  = "us-east-1"
env         = "devcql"
region      = "us-east-1"
zone1       = "us-east-1a"
zone2       = "us-east-1b"
eks_name    = "cloudquicklabs"
eks_version = "1.29"
