# three node (two workers) cluster config
kind: Cluster
name: rabbitmq-k8s
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
  - role: control-plane
    extraPortMappings:
      - containerPort: 31437   # Cluster port
        hostPort: 8080      # Localhost port
        protocol: TCP
      - containerPort: 31438   # Another cluster port
        hostPort: 8081      # Localhost port
        protocol: TCP
            # extraMounts:
    #   - hostPath: /mnt/data
    #     containerPath: /mnt/data

  - role: worker
    # extraPortMappings:
    #   - containerPort: 31437  # Cluster port
    #     hostPort: 8080        # Localhost port
    #     protocol: TCP
    #   - containerPort: 31438  # Another cluster port
    #     hostPort: 8081        # Localhost port
    #     protocol: TCP
        # extraMounts:
    #   - hostPath: /mnt/data
    #     containerPath: /mnt/data

  - role: worker
    # extraPortMappings:
    #   - containerPort: 31437  # Cluster port
    #     hostPort: 8080        # Localhost port
    #     protocol: TCP
    #   - containerPort: 31438  # Another cluster port
    #     hostPort: 8081        # Localhost port
    #     protocol: TCP
        # extraMounts:
    #   - hostPath: /mnt/data
    #     containerPath: /mnt/data
