apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: api-cert
  namespace: default
spec:
  # This secret will be our certificate we gonna use across the cluster 
  # (This is generated automatically)
  secretName: api-tls-secret
  dnsNames:
    - mydomain.com
    - www.mydomain.com
  issuerRef:
    kind: ClusterIssuer
    name: letsencrypt-issuer
    # group: cert-manager.io
