---
apiVersion: appmesh.k8s.aws/v1beta2
kind: GatewayRoute
metadata:
  namespace: server
  name: server-svc
spec:
  httpRoute:
    match:
      prefix: "/"
      hostname:
        exact: server-svc.devopsbyexample.com
    action:
      target:
        virtualService:
          virtualServiceRef:
            name: server-virtual-service
