---
apiVersion: v1
kind: ServiceAccount
metadata: # This Service Account has an IAM Role attached
  name: client-sa
  namespace: client
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::344743739159:role/devcql-cloudquicklabs-eks-client-svc # arn:aws:iam::[AWS User ID]:role/[K8S Cluster Role Name]
