---
apiVersion: appmesh.k8s.aws/v1beta2
kind: VirtualNode
metadata:
  name: client-virtual-node
  namespace: client
spec:
  podSelector:
    matchLabels:
      app: client-pod
  # The backends that the virtual node is expected to send outbound traffic to.
  backends:
    - virtualService:
        virtualServiceRef:
          namespace: server
          name: server-virtual-service
