apiVersion: v1
kind: Service
metadata:
  name: api-svc
  namespace: default
  labels:
    app: api-svc
spec:
  type: ClusterIP
  selector:
    app: api
  ports:
    - name: http
      procotol: TCP
      port: 80 # i am trying to acess, Service port
      targetPort: 8080 # inside API Container
