apiVersion: apps/v1
kind: DaemonSet
metadata:
  name:  my-name
  labels:
    name:  my-name
spec:
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  selector:
    matchLabels:
      name: fluent-bit
  template:
    metadata:
      labels:
        name: fluent-bit
    spec:
      containers:
      - name:  fluent-bit
        image:  fluent/fluent-bit:2.1.9
        resources:
          requests:
            cpu: "20m"
            memory: "55M"
        livenessProbe:
          httpGet:
            path: /_status/healthz
            port: 5000
          initialDelaySeconds: 90
          timeoutSeconds: 10
        readinessProbe:
          httpGet:
            path: /_status/healthz
            port: 5000
          initialDelaySeconds: 30
          timeoutSeconds: 10
        env:
        - name:  ENVVARNAME
          value:  ENVVARVALUE       
        ports:
        - containerPort:  5000
          name:  my-name
        volumeMounts:
        - mountPath: /data
          name: data
      volumes:
        - name: data
          emptyDir: {}
      restartPolicy: Always
      imagePullPolicy: Always
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: myapp
  namespace: default
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: StatefulSet
    name: myapp
  minReplicas: 1
  maxReplicas: 5
  metrics:
    - type: Resource # Scale up if CPU exceeds 80%
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 80
    - type: Resource # Scale up if Memory exceeds 70%
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: 70
