---
apiVersion: batch/v1
kind: Job
metadata:
  name: migration
spec:
  backoffLimit: 2
  template:
    metadata:
      name:  name
    spec:
      restartPolicy: Never
      containers:
        - name: migration
          image: ubuntu:22.04
          command:
            - echo
            - run migration

    