apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: node-exporter
  labels:
    app: prometheus
    component: node-exporter
spec:
  selector:
    matchLabels:
      app: prometheus
      component: node-exporter
  template:
    metadata:
      labels:
        app: prometheus
        component: node-exporter
    spec:
      containers:
        - name: node-exporter
          image: quay.io/prometheus/node-exporter:latest # Use the latest or specify a version
          ports:
            - containerPort: 9100                           # Expose metrics on port 9100
              name: metrics
          resources:
            limits:
              cpu: "100m"
              memory: "50Mi"
            requests:
              cpu: "50m"
              memory: "30Mi"
          securityContext:
            runAsNonRoot: true                            # Recommended for security
            allowPrivilegeEscalation: false
          args:
            - "--path.procfs=/host/proc"                    # Set path to /proc for metrics
            - "--path.sysfs=/host/sys"                      # Set path to /sys for metrics
            - "--collector.filesystem.ignored-mount-points" # Avoid metrics from ephemeral filesystems
            - "^/(dev|proc|sys|var/lib/docker/.+)($|/)"
          volumeMounts:
            - name: proc # Provides Node Exporter access to necessary system metrics from the host.
              mountPath: /host/proc
              readOnly: true
            - name: sys
              mountPath: /host/sys
              readOnly: true
            - name: root # Access to the root filesystem.
              mountPath: /rootfs
              readOnly: true
          volumes:
            - name: proc
              hostPath:
                path: /proc
            - name: sys
              hostPath:
                path: /sys
            - name: root
              hostPath:
                path: /

# kubectl port-forward <node-exporter-pod-name> 9100:9100
