---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: server
  name: server-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: server-svc
  template:
    metadata:
      labels:
        app: server-svc
    spec:
      serviceAccountName: server-sa
      containers:
        - name: server-svc
          image: rekhugopal/eksmeshdemo:latest # rekhugopal/eksmeshdemo:latest
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 8080
          startupProbe:
            tcpSocket:
              port: http
            initialDelaySeconds: 20
            periodSeconds: 5
          resources: {}
            # limits:
            #   memory: "128Mi"
            #   cpu: "500m"
